// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18DaEEAgEdy79rCcd2LM-Pcqi6vFakw4',
    appId: '1:324229384792:web:11f6f75e9befddc159182d',
    messagingSenderId: '324229384792',
    projectId: 'targetku',
    authDomain: 'targetku.firebaseapp.com',
    storageBucket: 'targetku.firebasestorage.app',
    measurementId: 'G-VC9EWKMLXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz8TOsKCS6-GmHmOOjDdUUlQSohzit8Rw',
    appId: '1:324229384792:android:2c8e32ba04b9f00159182d',
    messagingSenderId: '324229384792',
    projectId: 'targetku',
    storageBucket: 'targetku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnVAyHAorLtz3khwjTUtgExlLP3A_Mqc4',
    appId: '1:324229384792:ios:c9888f64c6cd228859182d',
    messagingSenderId: '324229384792',
    projectId: 'targetku',
    storageBucket: 'targetku.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiLayli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnVAyHAorLtz3khwjTUtgExlLP3A_Mqc4',
    appId: '1:324229384792:ios:c9888f64c6cd228859182d',
    messagingSenderId: '324229384792',
    projectId: 'targetku',
    storageBucket: 'targetku.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiLayli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD18DaEEAgEdy79rCcd2LM-Pcqi6vFakw4',
    appId: '1:324229384792:web:3a2cce0849fe9daf59182d',
    messagingSenderId: '324229384792',
    projectId: 'targetku',
    authDomain: 'targetku.firebaseapp.com',
    storageBucket: 'targetku.firebasestorage.app',
    measurementId: 'G-6JFR13276Q',
  );
}
